### ISSUE TITLE
Return exit code 1 on error

### ISSUE THREAD

**Issue by spanitz** [doroppu/yoso-gulp#18]
Some tasks doesn't return exit > 0 on error (eg. `webpack-build`). As it is supposed to be if an error was thrown during the build. Particularly crucial on a CI.

So maybe `process.exit(1);` should do the trick when the error was thrown or something like `.on('error', process.exit.bind(process, 1))` after the process pipes.

**Comment by spanitz** [comment]
This resolutions introduced another error (affects `build` and `serve`). Full trace below:

``` shell

/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/gulp-util/lib/PluginError.js:73:28)
    at buildHandler (/Users/johndoe/MyProject/node_modules/yoso-gulp/tasks/webpack-build.js:38:23)
    at /Users/johndoe/MyProject/node_modules/yoso-gulp/tasks/webpack-build.js:61:13
    at Tapable.<anonymous> (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:193:14)
    at Tapable.emitRecords (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:280:37)
    at Tapable.<anonymous> (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:186:11)
    at /Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:273:11
    at Tapable.applyPluginsAsync (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:270:8)
    at Tapable.<anonymous> (/Users/johndoe/MyProject/node_modules/yoso-gulp/node_modules/webpack/lib/Compiler.js:265:14)

**Comment by lukas-zech-software** [comment]
Typo sneaked in the code ...
