### ISSUE TITLE
Build raises an error due to an unconfigured subtask

### ISSUE THREAD

**Issue by spanitz** [doroppu/yoso-gulp#2]
```bash
$ gulp build
# ...
Error: Task build-release-scripts is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at /Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/node_modules/run-sequence/index.js:19:10
    at Array.forEach (native)
    at verifyTaskSets (/Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/node_modules/run-sequence/index.js:12:11)
    at /Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/node_modules/run-sequence/index.js:31:4
    at Array.forEach (native)
    at verifyTaskSets (/Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/node_modules/run-sequence/index.js:12:11)
    at runSequence (/Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/node_modules/run-sequence/index.js:80:2)
    at Gulp.<anonymous> (/Users/spanitz/Projects/gfke/planet-music/node_modules/yoso-gulp/tasks/build-release.js:33:5)
    at module.exports (/Users/spanitz/Projects/gfke/planet-music/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/spanitz/Projects/gfke/planet-music/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```

**Comment by spanitz** [comment]
This issue was fixed in (2.0.0)
